/**
 * Smart Library System - Frontend Application Logic
 * Supports Day 1 to Day 5 Features:
 * - Strict Account Architecture: Root Admin pre-seeded, Reader accounts generated by Admin
 * - Buy Flow & Rental Flow with OOP Polymorphism
 * - AudioBook streaming preview & E-Book reader
 * - FIFO Reservation Queue tracking
 * - Nearby Libraries search by city/pincode with distance sorting
 */

// State Management
const state = {
    currentUser: {
        userId: "admin",
        name: "System Administrator",
        email: "admin@library.edu",
        role: "ADMIN"
    },
    allBooks: [],
    myLoans: [],
    myPurchases: [],
    myReservations: [],
    adminTransactions: [],
    adminReservations: [],
    adminReaders: [],
    nearbyLibraries: [],
    activeFilter: "ALL",
    activeSort: "default",
    searchQuery: "",
    selectedBookForBorrow: null,
    selectedBookForBuy: null,
    borrowDays: 7
};

// ==========================================================================
// Initialization & Lifecycle
// ==========================================================================
document.addEventListener("DOMContentLoaded", () => {
    // Restore session if available
    const savedUser = localStorage.getItem("sls_user");
    if (savedUser) {
        try {
            state.currentUser = JSON.parse(savedUser);
        } catch (e) {}
    }

    updateUserUI();
    setupEventListeners();
    fetchHealth();
    fetchBooks();
    fetchNearbyLibraries("");
    fetchStats();

    if (state.currentUser) {
        fetchUserActivity();
    }
    if (isAdmin()) {
        fetchAdminData();
    }
});

function isAdmin() {
    return state.currentUser && (state.currentUser.role === "ADMIN" || state.currentUser.role === "SELLER");
}

function updateUserUI() {
    const avatar = document.getElementById("navUserAvatar");
    const nameEl = document.getElementById("navUserName");
    const roleEl = document.getElementById("navUserRole");
    const menuUserId = document.getElementById("menuCurrentUserId");
    const sellerTabBtn = document.getElementById("sellerTabBtn");
    const headerAddBtn = document.getElementById("headerActionAddBookBtn");

    if (state.currentUser) {
        const firstLetter = state.currentUser.name ? state.currentUser.name.charAt(0).toUpperCase() : "U";
        avatar.textContent = firstLetter;
        nameEl.textContent = state.currentUser.name || state.currentUser.userId;
        roleEl.textContent = state.currentUser.role;
        menuUserId.textContent = state.currentUser.userId;

        if (isAdmin()) {
            avatar.classList.add("admin-avatar");
            roleEl.className = "role-tag role-admin";
            if (sellerTabBtn) sellerTabBtn.style.display = "flex";
            if (headerAddBtn) headerAddBtn.style.display = "inline-flex";
        } else {
            avatar.classList.remove("admin-avatar");
            roleEl.className = "role-tag role-reader";
            if (sellerTabBtn) sellerTabBtn.style.display = "none";
            if (headerAddBtn) headerAddBtn.style.display = "none";
        }
    } else {
        avatar.textContent = "?";
        nameEl.textContent = "Guest";
        roleEl.textContent = "NOT SIGNED IN";
        menuUserId.textContent = "None";
        if (sellerTabBtn) sellerTabBtn.style.display = "none";
        if (headerAddBtn) headerAddBtn.style.display = "none";
    }
}

// ==========================================================================
// Event Listeners
// ==========================================================================
function setupEventListeners() {
    // Brand click resets to catalog tab
    document.getElementById("brandLogoBtn").addEventListener("click", () => switchTab("catalogTab"));

    // User Dropdown toggle
    const dropdownBtn = document.getElementById("userDropdownBtn");
    const dropdownMenu = document.getElementById("userDropdownMenu");
    dropdownBtn.addEventListener("click", (e) => {
        e.stopPropagation();
        dropdownMenu.classList.toggle("hidden");
    });
    document.addEventListener("click", () => dropdownMenu.classList.add("hidden"));

    // Dropdown Actions
    document.getElementById("switchRootAdminBtn").addEventListener("click", () => {
        loginUser("admin", "admin123");
    });

    document.getElementById("openAuthModalFromDropdown").addEventListener("click", () => {
        openModal("authModal");
    });

    document.getElementById("logoutDropdownBtn").addEventListener("click", () => {
        logoutUser();
    });

    // Navigation Tabs
    document.querySelectorAll(".tab-btn").forEach(btn => {
        btn.addEventListener("click", () => {
            const tabId = btn.getAttribute("data-tab");
            switchTab(tabId);
        });
    });

    // Admin Subtabs
    document.querySelectorAll(".subtab-btn").forEach(btn => {
        btn.addEventListener("click", () => {
            document.querySelectorAll(".subtab-btn").forEach(b => b.classList.remove("active"));
            document.querySelectorAll(".admin-subtab-content").forEach(c => c.classList.remove("active"));
            btn.classList.add("active");
            const subtabId = btn.getAttribute("data-subtab");
            const target = document.getElementById(subtabId);
            if (target) target.classList.add("active");
        });
    });

    // Storage DB Toggle
    document.getElementById("toggleDbBtn").addEventListener("click", toggleDatabaseMode);
    document.getElementById("dbModeBadge").addEventListener("click", toggleDatabaseMode);

    // Search & Filter
    const searchInput = document.getElementById("searchInput");
    const clearBtn = document.getElementById("clearSearchBtn");
    searchInput.addEventListener("input", (e) => {
        state.searchQuery = e.target.value;
        clearBtn.classList.toggle("hidden", !state.searchQuery);
        fetchBooks();
    });
    clearBtn.addEventListener("click", () => {
        searchInput.value = "";
        state.searchQuery = "";
        clearBtn.classList.add("hidden");
        fetchBooks();
    });

    document.getElementById("sortSelect").addEventListener("change", (e) => {
        state.activeSort = e.target.value;
        fetchBooks();
    });

    document.querySelectorAll(".filter-pill").forEach(pill => {
        pill.addEventListener("click", () => {
            document.querySelectorAll(".filter-pill").forEach(p => p.classList.remove("active"));
            pill.classList.add("active");
            state.activeFilter = pill.getAttribute("data-filter");
            fetchBooks();
        });
    });

    document.getElementById("resetCatalogFiltersBtn").addEventListener("click", () => {
        document.getElementById("searchInput").value = "";
        state.searchQuery = "";
        state.activeFilter = "ALL";
        state.activeSort = "default";
        document.getElementById("sortSelect").value = "default";
        document.querySelectorAll(".filter-pill").forEach(p => p.classList.toggle("active", p.getAttribute("data-filter") === "ALL"));
        fetchBooks();
    });

    // Nearby Libraries Search (Day 3)
    document.getElementById("nearbySearchBtn").addEventListener("click", () => {
        const query = document.getElementById("nearbySearchInput").value.trim();
        fetchNearbyLibraries(query);
    });
    document.getElementById("nearbySearchInput").addEventListener("keyup", (e) => {
        if (e.key === "Enter") {
            const query = e.target.value.trim();
            fetchNearbyLibraries(query);
        }
    });

    // Admin Reader Generator Form (User Directive)
    const genForm = document.getElementById("adminCreateReaderForm");
    genForm.addEventListener("submit", handleAdminCreateReader);

    document.getElementById("btnAutoGenerateId").addEventListener("click", () => {
        const rand = Math.floor(1000 + Math.random() * 9000);
        document.getElementById("genReaderId").value = "RDR-" + rand;
    });

    document.getElementById("btnAutoGeneratePass").addEventListener("click", () => {
        const rand = Math.floor(100 + Math.random() * 900);
        document.getElementById("genReaderPassword").value = "read@" + rand;
    });

    document.getElementById("btnCopyCreds").addEventListener("click", copyGeneratedCreds);

    // Add Book Modal Open
    const openAddBook = () => {
        if (!isAdmin()) {
            showToast("Only Administrator can add books.", "error");
            return;
        }
        document.getElementById("bookForm").reset();
        document.getElementById("bookModalTitle").textContent = "Add New Book";
        updateBookTypeFields();
        openModal("bookModal");
    };
    document.getElementById("openAddBookModalBtn").addEventListener("click", openAddBook);
    document.getElementById("headerActionAddBookBtn").addEventListener("click", openAddBook);
    document.getElementById("adminAddNewBookBtn").addEventListener("click", openAddBook);

    // Book Format Type Selector in Modal
    document.getElementById("bookTypeSelect").addEventListener("change", updateBookTypeFields);
    document.getElementById("bookForm").addEventListener("submit", handleSaveBook);

    // Borrow / Rent Modal controls
    const slider = document.getElementById("borrowDurationSlider");
    const sliderDisp = document.getElementById("borrowSliderDisplay");
    slider.addEventListener("input", (e) => {
        state.borrowDays = parseInt(e.target.value, 10);
        sliderDisp.textContent = state.borrowDays + " Days";
        updateBorrowCalculation();
        // Update preset buttons
        document.querySelectorAll(".duration-btn").forEach(btn => {
            btn.classList.toggle("active", parseInt(btn.getAttribute("data-days"), 10) === state.borrowDays);
        });
    });

    document.querySelectorAll(".duration-btn").forEach(btn => {
        btn.addEventListener("click", () => {
            const days = parseInt(btn.getAttribute("data-days"), 10);
            state.borrowDays = days;
            slider.value = days;
            sliderDisp.textContent = days + " Days";
            document.querySelectorAll(".duration-btn").forEach(b => b.classList.remove("active"));
            btn.classList.add("active");
            updateBorrowCalculation();
        });
    });

    document.getElementById("confirmBorrowBtn").addEventListener("click", confirmBorrowBook);
    document.getElementById("cancelBorrowBtn").addEventListener("click", () => closeModal("borrowModal"));
    document.getElementById("closeBorrowModalBtn").addEventListener("click", () => closeModal("borrowModal"));

    // Buy Modal controls (Day 4)
    document.getElementById("confirmBuyBtn").addEventListener("click", confirmBuyBook);
    document.getElementById("cancelBuyBtn").addEventListener("click", () => closeModal("buyModal"));
    document.getElementById("closeBuyModalBtn").addEventListener("click", () => closeModal("buyModal"));

    // Modal Close Buttons
    document.getElementById("closeBookModalBtn").addEventListener("click", () => closeModal("bookModal"));
    document.getElementById("cancelBookBtn").addEventListener("click", () => closeModal("bookModal"));

    document.getElementById("closeAudioPlayerBtn").addEventListener("click", () => closeModal("audioPlayerModal"));
    document.getElementById("closeAudioPlayerFooterBtn").addEventListener("click", () => closeModal("audioPlayerModal"));

    document.getElementById("closeEbookReaderBtn").addEventListener("click", () => closeModal("ebookReaderModal"));
    document.getElementById("closeReaderFooterBtn").addEventListener("click", () => closeModal("ebookReaderModal"));

    document.getElementById("closeAuthModalBtn").addEventListener("click", () => closeModal("authModal"));
    document.getElementById("loginForm").addEventListener("submit", handleLoginSubmit);

    document.getElementById("closeReceiptModalBtn").addEventListener("click", () => closeModal("receiptModal"));
    document.getElementById("closeReceiptBtn").addEventListener("click", () => {
        closeModal("receiptModal");
        fetchBooks();
        fetchUserActivity();
        fetchStats();
    });

    // Admin Transactions Filter
    const adminTxSearch = document.getElementById("adminTxSearchInput");
    const adminTxType = document.getElementById("adminTxTypeFilter");
    if (adminTxSearch) adminTxSearch.addEventListener("input", renderAdminTransactions);
    if (adminTxType) adminTxType.addEventListener("change", renderAdminTransactions);
}

function updateBookTypeFields() {
    const type = document.getElementById("bookTypeSelect").value;
    const shelfGroup = document.getElementById("shelfGroup");
    const linkGroup = document.getElementById("linkGroup");
    const narratorGroup = document.getElementById("audioNarratorGroup");
    const durationGroup = document.getElementById("audioDurationGroup");
    const urlGroup = document.getElementById("audioUrlGroup");

    shelfGroup.classList.toggle("hidden", type !== "PHYSICAL");
    linkGroup.classList.toggle("hidden", type !== "EBOOK");
    narratorGroup.classList.toggle("hidden", type !== "AUDIOBOOK");
    durationGroup.classList.toggle("hidden", type !== "AUDIOBOOK");
    urlGroup.classList.toggle("hidden", type !== "AUDIOBOOK");
}

function switchTab(tabId) {
    document.querySelectorAll(".tab-btn").forEach(btn => {
        btn.classList.toggle("active", btn.getAttribute("data-tab") === tabId);
    });
    document.querySelectorAll(".tab-content").forEach(content => {
        content.classList.toggle("active", content.id === tabId);
    });

    if (tabId === "myLoansTab" || tabId === "myReservationsTab") {
        fetchUserActivity();
    } else if (tabId === "sellerTab") {
        if (!isAdmin()) {
            showToast("Admin access only. Switched back to Catalog.", "error");
            switchTab("catalogTab");
            return;
        }
        fetchAdminData();
    } else if (tabId === "nearbyTab") {
        fetchNearbyLibraries(document.getElementById("nearbySearchInput").value.trim());
    }
}

// ==========================================================================
// API Calls & Data Fetching
// ==========================================================================

async function fetchHealth() {
    try {
        const res = await fetch("/api/health");
        if (res.ok) {
            const data = await res.json();
            const badge = document.getElementById("dbModeBadge");
            const text = document.getElementById("dbModeText");
            if (data.databaseMode) {
                text.textContent = "MySQL Storage";
                badge.style.background = "#ecfdf5";
                badge.style.color = "#059669";
                badge.style.borderColor = "#a7f3d0";
            } else {
                text.textContent = "In-Memory Mode";
                badge.style.background = "#eff6ff";
                badge.style.color = "#2563eb";
                badge.style.borderColor = "#bfdbfe";
            }
        }
    } catch (e) {
        document.getElementById("serverStatusText").textContent = "Reconnecting...";
    }
}

async function fetchStats() {
    try {
        const res = await fetch("/api/stats");
        if (res.ok) {
            const data = await res.json();
            document.getElementById("kpiTotalBooks").textContent = data.totalBooks || 0;
            document.getElementById("kpiAvailableBooks").textContent = data.availableBooks || 0;
            document.getElementById("kpiActiveLoans").textContent = data.activeLoans || 0;
            const digitalCount = (data.ebooks || 0) + (data.audioBooks || 0);
            document.getElementById("kpiDigitalMedia").textContent = digitalCount;
            document.getElementById("kpiRevenue").textContent = "₹" + (data.totalRevenue || 0).toLocaleString("en-IN");
        }
    } catch (e) {}
}

async function fetchBooks() {
    try {
        let url = `/api/books?sort=${state.activeSort}`;
        if (state.searchQuery) url += `&query=${encodeURIComponent(state.searchQuery)}`;
        if (state.activeFilter && state.activeFilter !== "ALL") url += `&type=${state.activeFilter}`;

        const res = await fetch(url);
        if (res.ok) {
            state.allBooks = await res.json();
            renderBooks();
            renderAdminInventory();
        }
    } catch (e) {
        showToast("Failed to fetch book catalog.", "error");
    }
}

async function fetchNearbyLibraries(query) {
    try {
        const url = query ? `/api/libraries/nearby?query=${encodeURIComponent(query)}` : "/api/libraries/nearby";
        const res = await fetch(url);
        if (res.ok) {
            state.nearbyLibraries = await res.json();
            renderNearbyLibraries();
        }
    } catch (e) {
        showToast("Could not load branch libraries.", "error");
    }
}

async function fetchUserActivity() {
    if (!state.currentUser) return;
    const userId = state.currentUser.userId;

    try {
        // Fetch transactions (both RENT and BUY)
        const txRes = await fetch(`/api/transactions?userId=${encodeURIComponent(userId)}`);
        if (txRes.ok) {
            const txList = await txRes.json();
            state.myLoans = txList.filter(t => t.transactionType === "RENT");
            state.myPurchases = txList.filter(t => t.transactionType === "BUY");
            renderMyLoans();
            document.getElementById("myLoansCountBadge").textContent = state.myLoans.filter(l => l.status === "BORROWED").length;
        }

        // Fetch reservations
        const resRes = await fetch(`/api/reservations?userId=${encodeURIComponent(userId)}`);
        if (resRes.ok) {
            state.myReservations = await resRes.json();
            renderMyReservations();
            document.getElementById("myReservationsCountBadge").textContent = state.myReservations.filter(r => r.status === "PENDING" || r.status === "READY").length;
        }
    } catch (e) {}
}

async function fetchAdminData() {
    if (!isAdmin()) return;

    try {
        // All transactions
        const txRes = await fetch("/api/transactions");
        if (txRes.ok) {
            state.adminTransactions = await txRes.json();
            renderAdminTransactions();
        }

        // All reservations
        const resRes = await fetch("/api/reservations");
        if (resRes.ok) {
            state.adminReservations = await resRes.json();
            renderAdminReservations();
        }

        // All readers
        const rdrRes = await fetch("/api/admin/readers");
        if (rdrRes.ok) {
            state.adminReaders = await rdrRes.json();
            renderAdminReaders();
        }
    } catch (e) {}
}

// ==========================================================================
// Rendering: Book Catalog & Cards
// ==========================================================================
function renderBooks() {
    const grid = document.getElementById("booksGrid");
    const emptyState = document.getElementById("emptyCatalogState");
    grid.innerHTML = "";

    if (!state.allBooks || state.allBooks.length === 0) {
        emptyState.classList.remove("hidden");
        return;
    }
    emptyState.classList.add("hidden");

    state.allBooks.forEach(book => {
        const card = document.createElement("div");
        card.className = "book-card";

        const type = (book.bookType || "PHYSICAL").toUpperCase();
        let badgeClass = "type-physical";
        let formatLabel = "Physical Book";
        let locationDetail = `Shelf #${book.shelfNumber || 100}`;

        if (type === "EBOOK") {
            badgeClass = "type-ebook";
            formatLabel = "Digital E-Book";
            locationDetail = "Digital Cloud Access (PDF)";
        } else if (type === "AUDIOBOOK") {
            badgeClass = "type-audiobook";
            formatLabel = "AudioBook";
            locationDetail = `Narrated by ${book.narrator || "Author"} (${book.audioDurationMinutes || 180}m)`;
        }

        const isAvailable = book.availableCopies > 0 || book.isAvailable;
        const rentalRate = book.rentalPricePerDay || (type === "EBOOK" ? 10 : (type === "AUDIOBOOK" ? 15 : 20));
        const buyPrice = book.buyPrice || 499;

        card.innerHTML = `
            <div>
                <div class="book-top-bar">
                    <span class="book-type-badge ${badgeClass}">${formatLabel}</span>
                    <span class="book-genre-tag">${escapeHtml(book.genre || "General")}</span>
                </div>
                <h3 class="book-title">${escapeHtml(book.title)}</h3>
                <p class="book-author">by ${escapeHtml(book.author)}</p>

                <div class="book-meta-grid">
                    <div class="meta-item">
                        <span class="meta-label">Rental Rate</span>
                        <span class="meta-val rate-highlight">₹${rentalRate}/day</span>
                    </div>
                    <div class="meta-item">
                        <span class="meta-label">Buy Price</span>
                        <span class="meta-val buy-highlight">₹${buyPrice}</span>
                    </div>
                    <div class="meta-item">
                        <span class="meta-label">Availability</span>
                        <span class="meta-val" style="color: ${isAvailable ? '#059669' : '#dc2626'}">
                            ${isAvailable ? `In Stock (${book.availableCopies || 1})` : "Checked Out"}
                        </span>
                    </div>
                    <div class="meta-item">
                        <span class="meta-label">Format Detail</span>
                        <span class="meta-val" style="font-size: 0.75rem;">${escapeHtml(locationDetail)}</span>
                    </div>
                </div>
            </div>

            <div>
                ${type === "AUDIOBOOK" ? `
                    <button class="btn btn-outline btn-sm btn-block" style="margin-bottom: 0.6rem; color: #7c3aed; border-color: #ddd6fe;" onclick="openAudioPlayer('${book.bookId}')">
                        🎧 Listen Sample Preview
                    </button>
                ` : ""}

                ${type === "EBOOK" ? `
                    <button class="btn btn-outline btn-sm btn-block" style="margin-bottom: 0.6rem; color: #2563eb; border-color: #bfdbfe;" onclick="openEbookReader('${book.bookId}')">
                        📖 Preview E-Book
                    </button>
                ` : ""}

                <div class="book-actions">
                    ${isAvailable ? `
                        <button class="btn btn-outline-primary btn-sm" onclick="openBorrowModal('${book.bookId}')">
                            Rent Book
                        </button>
                        <button class="btn btn-success btn-sm" onclick="openBuyModal('${book.bookId}')">
                            Buy (₹${buyPrice})
                        </button>
                    ` : `
                        <button class="btn btn-primary btn-sm book-actions-full" onclick="reserveBook('${book.bookId}')">
                            ⏳ Reserve Copy (FIFO Queue)
                        </button>
                    `}
                </div>
            </div>
        `;
        grid.appendChild(card);
    });
}

// ==========================================================================
// Rendering: Nearby Libraries (Day 3 Feature)
// ==========================================================================
function renderNearbyLibraries() {
    const grid = document.getElementById("nearbyLibrariesGrid");
    grid.innerHTML = "";

    if (!state.nearbyLibraries || state.nearbyLibraries.length === 0) {
        grid.innerHTML = `
            <div class="empty-state full-width" style="grid-column: 1 / -1;">
                <div class="empty-icon">📍</div>
                <h3>No Libraries Found</h3>
                <p>No branch libraries match your search location. Try "Delhi", "Mumbai", or "110001".</p>
            </div>
        `;
        return;
    }

    state.nearbyLibraries.forEach(lib => {
        const card = document.createElement("div");
        card.className = "library-card";
        card.innerHTML = `
            <div>
                <div class="lib-header">
                    <h3 class="lib-title">${escapeHtml(lib.name)}</h3>
                    <span class="lib-dist-badge">📍 ${lib.distanceKm} km away</span>
                </div>
                <p class="lib-address">${escapeHtml(lib.location)}, ${escapeHtml(lib.city)} - ${escapeHtml(lib.pincode)}</p>
                
                <div class="lib-meta">
                    <div><strong>City / Pincode:</strong> ${escapeHtml(lib.city)} (${escapeHtml(lib.pincode)})</div>
                    <div><strong>Contact:</strong> ${escapeHtml(lib.contactNumber || "+91 11 2345 6789")}</div>
                    <div><strong>Branch ID:</strong> <code>${escapeHtml(lib.libraryId)}</code></div>
                </div>
            </div>

            <div style="margin-top: 1.15rem; display: flex; gap: 0.5rem;">
                <button class="btn btn-outline-primary btn-sm btn-block" onclick="showToast('Branch books synced with central catalog.', 'info')">
                    View Branch Catalog
                </button>
            </div>
        `;
        grid.appendChild(card);
    });
}

// ==========================================================================
// Rendering: My Loans & Purchases Tab (Day 4)
// ==========================================================================
function renderMyLoans() {
    const container = document.getElementById("myLoansList");
    container.innerHTML = "";

    // 1. Active & Past Rental Loans
    const loansHeader = document.createElement("h3");
    loansHeader.textContent = "📖 Rented Books (Active & History)";
    loansHeader.style.marginBottom = "0.75rem";
    loansHeader.style.fontSize = "1.1rem";
    container.appendChild(loansHeader);

    if (state.myLoans.length === 0) {
        const emptyLoans = document.createElement("div");
        emptyLoans.className = "empty-state";
        emptyLoans.style.marginBottom = "2rem";
        emptyLoans.innerHTML = `
            <div class="empty-icon">📚</div>
            <p>You have no rented books. Explore the catalog and borrow books to see them here.</p>
        `;
        container.appendChild(emptyLoans);
    } else {
        const tableBox = document.createElement("div");
        tableBox.className = "table-responsive";
        tableBox.style.marginBottom = "2.5rem";
        tableBox.innerHTML = `
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Tx ID</th>
                        <th>Book Title</th>
                        <th>Borrowed Date</th>
                        <th>Due Date</th>
                        <th>Rental Fee</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody id="myLoansTbody"></tbody>
            </table>
        `;
        container.appendChild(tableBox);
        const tbody = tableBox.querySelector("#myLoansTbody");

        state.myLoans.forEach(loan => {
            const isBorrowed = loan.status === "BORROWED";
            const tr = document.createElement("tr");
            tr.innerHTML = `
                <td><code>${loan.transactionId}</code></td>
                <td><strong>${escapeHtml(loan.bookTitle)}</strong></td>
                <td>${loan.issueDate}</td>
                <td>${loan.dueDate || "N/A"}</td>
                <td>₹${loan.rentalPrice || loan.amountPaid}</td>
                <td>
                    <span class="badge ${isBorrowed ? 'badge-warning' : 'badge-success'}">
                        ${loan.status}
                    </span>
                </td>
                <td>
                    ${isBorrowed ? `
                        <button class="btn btn-primary btn-sm" onclick="returnBook('${loan.transactionId}')">
                            Return Book
                        </button>
                    ` : `
                        <span style="font-size: 0.78rem; color: var(--text-muted);">Returned on ${loan.returnDate}</span>
                    `}
                </td>
            `;
            tbody.appendChild(tr);
        });
    }

    // 2. Permanently Purchased Books (Day 4: Buy Flow)
    const purchaseHeader = document.createElement("h3");
    purchaseHeader.textContent = "💎 Permanently Purchased Books";
    purchaseHeader.style.marginBottom = "0.75rem";
    purchaseHeader.style.fontSize = "1.1rem";
    container.appendChild(purchaseHeader);

    if (state.myPurchases.length === 0) {
        const emptyPurchases = document.createElement("div");
        emptyPurchases.className = "empty-state";
        emptyPurchases.innerHTML = `
            <div class="empty-icon">💎</div>
            <p>You haven't purchased any books permanently yet. Click "Buy" on any book in the catalog!</p>
        `;
        container.appendChild(emptyPurchases);
    } else {
        const purchaseBox = document.createElement("div");
        purchaseBox.className = "table-responsive";
        purchaseBox.innerHTML = `
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Order ID</th>
                        <th>Book Title</th>
                        <th>Purchased Date</th>
                        <th>Price Paid</th>
                        <th>Ownership Status</th>
                    </tr>
                </thead>
                <tbody id="myPurchasesTbody"></tbody>
            </table>
        `;
        container.appendChild(purchaseBox);
        const pbody = purchaseBox.querySelector("#myPurchasesTbody");

        state.myPurchases.forEach(p => {
            const tr = document.createElement("tr");
            tr.innerHTML = `
                <td><code>${p.transactionId}</code></td>
                <td><strong>${escapeHtml(p.bookTitle)}</strong></td>
                <td>${p.issueDate}</td>
                <td><strong style="color: #059669;">₹${p.amountPaid}</strong></td>
                <td>
                    <span class="badge badge-success">PERMANENTLY OWNED</span>
                </td>
            `;
            pbody.appendChild(tr);
        });
    }
}

// ==========================================================================
// Rendering: My Reservations Tab (FIFO Queue)
// ==========================================================================
function renderMyReservations() {
    const container = document.getElementById("myReservationsList");
    container.innerHTML = "";

    if (state.myReservations.length === 0) {
        container.innerHTML = `
            <div class="empty-state">
                <div class="empty-icon">⏳</div>
                <h3>No Active Reservations</h3>
                <p>When books are currently loaned out, reserve them to enter the FIFO priority queue.</p>
            </div>
        `;
        return;
    }

    const tableBox = document.createElement("div");
    tableBox.className = "table-responsive";
    tableBox.innerHTML = `
        <table class="data-table">
            <thead>
                <tr>
                    <th>Hold ID</th>
                    <th>Book Title</th>
                    <th>Date Reserved</th>
                    <th>FIFO Queue Position</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody id="myResTbody"></tbody>
        </table>
    `;
    container.appendChild(tableBox);
    const tbody = tableBox.querySelector("#myResTbody");

    state.myReservations.forEach(res => {
        const isReady = res.status === "READY";
        const tr = document.createElement("tr");
        tr.innerHTML = `
            <td><code>${res.reservationId}</code></td>
            <td><strong>${escapeHtml(res.bookTitle)}</strong></td>
            <td>${res.reservationDate}</td>
            <td>
                <span class="badge ${isReady ? 'badge-success' : 'badge-info'}">
                    ${isReady ? '🎉 NEXT IN LINE (READY)' : `#${res.queuePosition || 1} in FIFO Queue`}
                </span>
            </td>
            <td>
                <span class="badge ${isReady ? 'badge-success' : (res.status === 'PENDING' ? 'badge-warning' : 'badge-purple')}">
                    ${res.status}
                </span>
            </td>
            <td>
                ${isReady ? `
                    <button class="btn btn-success btn-sm" onclick="claimReservation('${res.reservationId}')">
                        Claim & Rent Book
                    </button>
                ` : `
                    <button class="btn btn-outline btn-sm text-danger" onclick="cancelReservation('${res.reservationId}')">
                        Cancel Hold
                    </button>
                `}
            </td>
        `;
        tbody.appendChild(tr);
    });
}

// ==========================================================================
// Rendering: Admin Panel Views (Day 5 & User Directives)
// ==========================================================================
function renderAdminReaders() {
    const tbody = document.getElementById("adminReadersTbody");
    const countBadge = document.getElementById("adminReaderCount");
    tbody.innerHTML = "";

    if (!state.adminReaders || state.adminReaders.length === 0) {
        tbody.innerHTML = `
            <tr>
                <td colspan="5" style="text-align: center; color: var(--text-muted); padding: 2rem;">
                    No reader accounts generated yet. Use the form on the left to generate credentials.
                </td>
            </tr>
        `;
        countBadge.textContent = "0 Readers";
        return;
    }

    countBadge.textContent = `${state.adminReaders.length} Readers`;

    state.adminReaders.forEach(reader => {
        const tr = document.createElement("tr");
        tr.innerHTML = `
            <td><code>${escapeHtml(reader.userId)}</code></td>
            <td><strong>${escapeHtml(reader.name)}</strong></td>
            <td>${escapeHtml(reader.email || "N/A")}</td>
            <td>
                <span style="font-family: var(--font-mono); background: #f1f5f9; padding: 0.15rem 0.45rem; border-radius: 4px;">
                    ${escapeHtml(reader.password)}
                </span>
            </td>
            <td>
                <button class="btn btn-outline btn-sm text-danger" onclick="deleteReader('${reader.userId}')">
                    Delete
                </button>
            </td>
        `;
        tbody.appendChild(tr);
    });
}

function renderAdminInventory() {
    const tbody = document.getElementById("adminInventoryTbody");
    if (!tbody) return;
    tbody.innerHTML = "";

    state.allBooks.forEach(b => {
        const tr = document.createElement("tr");
        tr.innerHTML = `
            <td><code>${b.bookId}</code></td>
            <td><strong>${escapeHtml(b.title)}</strong></td>
            <td>${escapeHtml(b.author)}</td>
            <td><span class="book-genre-tag">${escapeHtml(b.genre || "General")}</span></td>
            <td><span class="badge badge-info">${b.bookType}</span></td>
            <td>₹${b.rentalPricePerDay || 20}/d</td>
            <td><strong style="color: #059669;">₹${b.buyPrice || 499}</strong></td>
            <td>${b.availableCopies || (b.isAvailable ? 1 : 0)} / ${b.totalCopies || 1}</td>
            <td>
                <button class="btn btn-outline btn-sm text-danger" onclick="deleteBook('${b.bookId}')">
                    Delete
                </button>
            </td>
        `;
        tbody.appendChild(tr);
    });
}

function renderAdminTransactions() {
    const tbody = document.getElementById("adminTxTbody");
    const countBadge = document.getElementById("adminTxCount");
    if (!tbody) return;
    tbody.innerHTML = "";

    const search = document.getElementById("adminTxSearchInput")?.value.toLowerCase() || "";
    const typeFilter = document.getElementById("adminTxTypeFilter")?.value || "ALL";

    const filtered = state.adminTransactions.filter(t => {
        const matchSearch = !search ||
            (t.userId && t.userId.toLowerCase().includes(search)) ||
            (t.bookTitle && t.bookTitle.toLowerCase().includes(search)) ||
            (t.transactionId && t.transactionId.toLowerCase().includes(search));

        const matchType = typeFilter === "ALL" || (t.transactionType === typeFilter);
        return matchSearch && matchType;
    });

    countBadge.textContent = `${filtered.length} Transactions`;

    filtered.forEach(tx => {
        const tr = document.createElement("tr");
        const isBuy = tx.transactionType === "BUY";
        tr.innerHTML = `
            <td><code>${tx.transactionId}</code></td>
            <td><strong>${escapeHtml(tx.userId)}</strong></td>
            <td>${escapeHtml(tx.bookTitle)}</td>
            <td>
                <span class="badge ${isBuy ? 'badge-success' : 'badge-info'}">
                    ${tx.transactionType || "RENT"}
                </span>
            </td>
            <td>${tx.issueDate}</td>
            <td>${tx.dueDate || "N/A"}</td>
            <td>₹${tx.amountPaid}</td>
            <td>₹${tx.overdueFine || 0}</td>
            <td>
                <span class="badge ${tx.status === 'BORROWED' ? 'badge-warning' : (tx.status === 'PURCHASED' ? 'badge-success' : 'badge-purple')}">
                    ${tx.status}
                </span>
            </td>
        `;
        tbody.appendChild(tr);
    });
}

function renderAdminReservations() {
    const tbody = document.getElementById("adminResTbody");
    const countBadge = document.getElementById("adminResCount");
    if (!tbody) return;
    tbody.innerHTML = "";

    countBadge.textContent = `${state.adminReservations.length} Reservations`;

    state.adminReservations.forEach(r => {
        const tr = document.createElement("tr");
        tr.innerHTML = `
            <td><code>${r.reservationId}</code></td>
            <td><strong>${escapeHtml(r.userId)}</strong></td>
            <td>${escapeHtml(r.bookTitle || r.bookId)}</td>
            <td><span class="badge badge-info">#${r.queuePosition || 1} in FIFO Queue</span></td>
            <td>${r.reservationDate}</td>
            <td>
                <span class="badge ${r.status === 'READY' ? 'badge-success' : 'badge-warning'}">
                    ${r.status}
                </span>
            </td>
        `;
        tbody.appendChild(tr);
    });
}

// ==========================================================================
// User Directive: Admin Reader Generator Actions
// ==========================================================================
async function handleAdminCreateReader(e) {
    e.preventDefault();

    const name = document.getElementById("genReaderName").value.trim();
    const email = document.getElementById("genReaderEmail").value.trim();
    const customId = document.getElementById("genReaderId").value.trim();
    const password = document.getElementById("genReaderPassword").value.trim();

    // Day 1 email regex check
    const emailRegex = /^[a-zA-Z0-9_+&*-]+(?:\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,7}$/;
    if (!emailRegex.test(email)) {
        showToast("Invalid email address. Please provide a valid email.", "error");
        return;
    }

    // Day 1 password length check
    if (password.length < 6) {
        showToast("Password must be at least 6 characters long.", "error");
        return;
    }

    try {
        const res = await fetch("/api/admin/create-reader", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ userId: customId, name, email, password })
        });

        const data = await res.json();
        if (res.ok && data.success) {
            showToast("🎉 Reader account created & activated successfully!", "success");

            // Display credentials box
            const box = document.getElementById("generatedCredBox");
            document.getElementById("dispGenId").textContent = data.reader.userId;
            document.getElementById("dispGenName").textContent = data.reader.name;
            document.getElementById("dispGenEmail").textContent = data.reader.email;
            document.getElementById("dispGenPass").textContent = data.reader.password;
            box.classList.remove("hidden");

            // Reset form
            document.getElementById("adminCreateReaderForm").reset();

            // Refresh readers list
            fetchAdminData();
        } else {
            showToast(data.error || "Failed to create reader.", "error");
        }
    } catch (e) {
        showToast("Network error creating reader account.", "error");
    }
}

function copyGeneratedCreds() {
    const id = document.getElementById("dispGenId").textContent;
    const name = document.getElementById("dispGenName").textContent;
    const email = document.getElementById("dispGenEmail").textContent;
    const pass = document.getElementById("dispGenPass").textContent;

    const text = `Smart Library System - Reader Login Credentials:\nName: ${name}\nReader ID: ${id}\nEmail: ${email}\nPassword: ${pass}\nPortal: http://localhost:8080/`;
    navigator.clipboard.writeText(text).then(() => {
        showToast("📋 Credentials copied to clipboard!", "success");
    }).catch(() => {
        showToast("Failed to copy automatically. Please copy manually.", "info");
    });
}

async function deleteReader(userId) {
    if (!confirm(`Are you sure you want to delete reader ${userId}?`)) return;

    try {
        const res = await fetch(`/api/admin/readers/delete?userId=${encodeURIComponent(userId)}`, {
            method: "DELETE"
        });
        const data = await res.json();
        if (res.ok && data.success) {
            showToast("Reader deleted successfully.", "success");
            fetchAdminData();
        } else {
            showToast(data.error || "Failed to delete reader.", "error");
        }
    } catch (e) {
        showToast("Error deleting reader.", "error");
    }
}

// ==========================================================================
// Rental & Borrow Flow (OOP Polymorphism)
// ==========================================================================
function openBorrowModal(bookId) {
    if (!state.currentUser) {
        showToast("Please sign in first to borrow books.", "error");
        openModal("authModal");
        return;
    }

    const book = state.allBooks.find(b => b.bookId === bookId);
    if (!book) return;

    state.selectedBookForBorrow = book;
    document.getElementById("borrowModalTitle").textContent = book.title;
    document.getElementById("borrowModalAuthor").textContent = `by ${book.author}`;
    document.getElementById("borrowUserIdInput").value = `${state.currentUser.name} (${state.currentUser.userId})`;

    const type = (book.bookType || "PHYSICAL").toUpperCase();
    const typeBadge = document.getElementById("borrowModalType");
    typeBadge.textContent = type;
    typeBadge.className = `book-type-badge ${type === 'EBOOK' ? 'type-ebook' : (type === 'AUDIOBOOK' ? 'type-audiobook' : 'type-physical')}`;

    state.borrowDays = 7;
    document.getElementById("borrowDurationSlider").value = 7;
    document.getElementById("borrowSliderDisplay").textContent = "7 Days";
    document.querySelectorAll(".duration-btn").forEach(b => b.classList.toggle("active", b.getAttribute("data-days") === "7"));

    updateBorrowCalculation();
    openModal("borrowModal");
}

function updateBorrowCalculation() {
    if (!state.selectedBookForBorrow) return;
    const book = state.selectedBookForBorrow;
    const type = (book.bookType || "PHYSICAL").toUpperCase();
    const dailyRate = book.rentalPricePerDay || (type === "EBOOK" ? 10 : (type === "AUDIOBOOK" ? 15 : 20));
    const total = dailyRate * state.borrowDays;

    document.getElementById("borrowModalRatePreview").textContent = `₹${dailyRate.toFixed(2)} / day`;
    document.getElementById("calcDailyRate").textContent = `₹${dailyRate.toFixed(2)}`;
    document.getElementById("calcDuration").textContent = `${state.borrowDays} days`;
    document.getElementById("calcTotal").textContent = `₹${total.toFixed(2)}`;

    // Calculate Due Date
    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + state.borrowDays);
    document.getElementById("calcDueDate").textContent = dueDate.toISOString().split("T")[0];

    document.getElementById("calcFormulaNote").textContent =
        `OOP Polymorphism: ${type === 'EBOOK' ? 'EBook' : (type === 'AUDIOBOOK' ? 'AudioBook' : 'PhysicalBook')}.getRentalPrice(${state.borrowDays}) -> ${state.borrowDays} × ₹${dailyRate.toFixed(2)} = ₹${total.toFixed(2)}`;
}

async function confirmBorrowBook() {
    if (!state.selectedBookForBorrow || !state.currentUser) return;

    try {
        const res = await fetch("/api/borrow", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                userId: state.currentUser.userId,
                bookId: state.selectedBookForBorrow.bookId,
                days: state.borrowDays
            })
        });

        const data = await res.json();
        if (res.ok) {
            closeModal("borrowModal");
            showToast(`✅ Successfully borrowed '${state.selectedBookForBorrow.title}'!`, "success");
            fetchBooks();
            fetchUserActivity();
            fetchStats();
        } else {
            showToast(data.error || "Failed to borrow book.", "error");
        }
    } catch (e) {
        showToast("Network error borrowing book.", "error");
    }
}

// ==========================================================================
// Buy Flow (Day 4 Requirement)
// ==========================================================================
function openBuyModal(bookId) {
    if (!state.currentUser) {
        showToast("Please sign in first to purchase books.", "error");
        openModal("authModal");
        return;
    }

    const book = state.allBooks.find(b => b.bookId === bookId);
    if (!book) return;

    state.selectedBookForBuy = book;
    document.getElementById("buyModalTitle").textContent = book.title;
    document.getElementById("buyModalAuthor").textContent = `by ${book.author}`;
    document.getElementById("buyModalPrice").textContent = `₹${book.buyPrice || 499}`;
    document.getElementById("buyUserIdInput").value = `${state.currentUser.name} (${state.currentUser.userId})`;

    openModal("buyModal");
}

async function confirmBuyBook() {
    if (!state.selectedBookForBuy || !state.currentUser) return;

    try {
        const res = await fetch("/api/buy", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                userId: state.currentUser.userId,
                bookId: state.selectedBookForBuy.bookId
            })
        });

        const data = await res.json();
        if (res.ok && data.success) {
            closeModal("buyModal");
            showToast(`🎉 Purchased '${state.selectedBookForBuy.title}' permanently!`, "success");
            fetchBooks();
            fetchUserActivity();
            fetchStats();
            switchTab("myLoansTab");
        } else {
            showToast(data.error || "Purchase failed.", "error");
        }
    } catch (e) {
        showToast("Network error executing book purchase.", "error");
    }
}

// ==========================================================================
// Return Flow with Receipt & FIFO Queue Notification
// ==========================================================================
async function returnBook(txId) {
    try {
        const res = await fetch("/api/return", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ transactionId: txId })
        });

        const receipt = await res.json();
        if (res.ok) {
            const tx = receipt.transaction;
            const content = document.getElementById("receiptContent");

            content.innerHTML = `
                <div style="background: #f8fafc; border: 1px solid var(--border-subtle); border-radius: var(--radius-md); padding: 1.25rem; margin-bottom: 1rem;">
                    <div style="display: flex; justify-content: space-between; margin-bottom: 0.5rem;">
                        <span style="font-size: 0.8rem; color: var(--text-muted);">Transaction ID</span>
                        <code>${tx.transactionId}</code>
                    </div>
                    <div style="font-weight: 700; color: var(--text-main); font-size: 1.05rem; margin-bottom: 0.25rem;">
                        ${escapeHtml(tx.bookTitle)}
                    </div>
                    <div style="font-size: 0.84rem; color: var(--text-secondary); margin-bottom: 0.75rem;">
                        Returned by: <strong>${escapeHtml(tx.userId)}</strong> on ${tx.returnDate}
                    </div>

                    <div style="border-top: 1px solid var(--border-subtle); padding-top: 0.75rem; display: flex; flex-direction: column; gap: 0.35rem; font-size: 0.85rem;">
                        <div style="display: flex; justify-content: space-between;">
                            <span>Rental Fee Paid:</span>
                            <span>₹${tx.rentalPrice || tx.amountPaid}</span>
                        </div>
                        <div style="display: flex; justify-content: space-between;">
                            <span>Days Overdue:</span>
                            <span style="color: ${receipt.daysLate > 0 ? '#dc2626' : 'var(--text-secondary)'}; font-weight: 700;">
                                ${receipt.daysLate || 0} days
                            </span>
                        </div>
                        <div style="display: flex; justify-content: space-between;">
                            <span>Late Return Fine (₹15/day):</span>
                            <span style="color: ${receipt.overdueFine > 0 ? '#dc2626' : 'var(--text-secondary)'}; font-weight: 700;">
                                ₹${receipt.overdueFine || 0}
                            </span>
                        </div>
                        <div style="border-top: 1px solid var(--border-subtle); margin-top: 0.25rem; padding-top: 0.5rem; display: flex; justify-content: space-between; font-weight: 800; font-size: 1rem; color: var(--text-main);">
                            <span>Total Settled:</span>
                            <span style="color: var(--color-primary);">₹${receipt.totalPaid || tx.totalAmount}</span>
                        </div>
                    </div>
                </div>

                ${receipt.reservationAlert ? `
                    <div style="background: #f0fdf4; border: 1.5px solid #a7f3d0; border-radius: var(--radius-md); padding: 1rem; font-size: 0.84rem; color: #166534;">
                        <strong>🔔 FIFO Queue Notification:</strong><br>
                        ${escapeHtml(receipt.reservationAlert)}
                    </div>
                ` : `
                    <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: var(--radius-md); padding: 0.75rem 1rem; font-size: 0.82rem; color: #1e40af;">
                        ℹ️ Inventory copy marked available for general checkout.
                    </div>
                `}
            `;

            openModal("receiptModal");
        } else {
            showToast(receipt.error || "Failed to return book.", "error");
        }
    } catch (e) {
        showToast("Network error returning book.", "error");
    }
}

// ==========================================================================
// Reservation Flow (FIFO Queue)
// ==========================================================================
async function reserveBook(bookId) {
    if (!state.currentUser) {
        showToast("Please sign in first to reserve books.", "error");
        openModal("authModal");
        return;
    }

    try {
        const res = await fetch("/api/reserve", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
                userId: state.currentUser.userId,
                bookId: bookId
            })
        });

        const data = await res.json();
        if (res.ok) {
            showToast(`⏳ Book reserved! You are #${data.queuePosition || 1} in the FIFO queue.`, "success");
            fetchUserActivity();
        } else {
            showToast(data.error || "Reservation failed.", "error");
        }
    } catch (e) {
        showToast("Network error reserving book.", "error");
    }
}

async function claimReservation(reservationId) {
    try {
        const res = await fetch("/api/reservations/claim", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ reservationId, days: 7 })
        });
        const data = await res.json();
        if (res.ok && data.success) {
            showToast("🎉 Book issued to you successfully!", "success");
            fetchBooks();
            fetchUserActivity();
            fetchStats();
        } else {
            showToast(data.error || "Unable to claim reservation.", "error");
        }
    } catch (e) {
        showToast("Error claiming reservation.", "error");
    }
}

async function cancelReservation(reservationId) {
    try {
        const res = await fetch(`/api/reserve?id=${encodeURIComponent(reservationId)}`, {
            method: "DELETE"
        });
        const data = await res.json();
        if (res.ok && data.success) {
            showToast("Reservation cancelled.", "info");
            fetchUserActivity();
        } else {
            showToast("Could not cancel reservation.", "error");
        }
    } catch (e) {
        showToast("Network error.", "error");
    }
}

// ==========================================================================
// AudioBook & EBook Preview Modals
// ==========================================================================
function openAudioPlayer(bookId) {
    const book = state.allBooks.find(b => b.bookId === bookId);
    if (!book) return;

    document.getElementById("audioModalTitle").textContent = book.title;
    document.getElementById("audioModalAuthor").textContent = `by ${book.author}`;
    document.getElementById("audioModalNarrator").textContent =
        `Narrated by ${book.narrator || "Author"} (${book.audioDurationMinutes || 180} mins)`;

    openModal("audioPlayerModal");
}

function openEbookReader(bookId) {
    const book = state.allBooks.find(b => b.bookId === bookId);
    if (!book) return;

    document.getElementById("readerModalTitle").textContent = book.title;
    document.getElementById("readerModalAuthor").textContent = `by ${book.author}`;
    const link = document.getElementById("readerDirectDownloadLink");
    link.href = book.downloadLink || "#";

    openModal("ebookReaderModal");
}

// ==========================================================================
// Book Creation & Management (Admin Only)
// ==========================================================================
async function handleSaveBook(e) {
    e.preventDefault();
    if (!isAdmin()) {
        showToast("Admin access required.", "error");
        return;
    }

    const bookId = document.getElementById("bookIdInput").value.trim();
    const title = document.getElementById("bookTitleInput").value.trim();
    const author = document.getElementById("bookAuthorInput").value.trim();
    const genre = document.getElementById("bookGenreInput").value.trim();
    const bookType = document.getElementById("bookTypeSelect").value;
    const buyPrice = parseFloat(document.getElementById("bookBuyPriceInput").value) || 499;

    const payload = { bookId, title, author, genre, bookType, buyPrice };

    if (bookType === "PHYSICAL") {
        payload.shelfNumber = parseInt(document.getElementById("shelfInput").value, 10) || 100;
    } else if (bookType === "EBOOK") {
        payload.downloadLink = document.getElementById("linkInput").value.trim();
    } else if (bookType === "AUDIOBOOK") {
        payload.narrator = document.getElementById("audioNarratorInput").value.trim() || "Author";
        payload.audioDurationMinutes = parseInt(document.getElementById("audioDurationInput").value, 10) || 180;
        payload.audioStreamUrl = document.getElementById("audioUrlInput").value.trim();
    }

    try {
        const res = await fetch("/api/books", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload)
        });

        if (res.ok) {
            closeModal("bookModal");
            showToast(`✅ Book '${title}' saved to catalog!`, "success");
            fetchBooks();
            fetchStats();
        } else {
            const err = await res.json();
            showToast(err.error || "Failed to save book.", "error");
        }
    } catch (e) {
        showToast("Network error saving book.", "error");
    }
}

async function deleteBook(bookId) {
    if (!isAdmin()) return;
    if (!confirm(`Are you sure you want to remove book ${bookId} from catalog?`)) return;

    try {
        const res = await fetch(`/api/books?id=${encodeURIComponent(bookId)}`, {
            method: "DELETE"
        });
        if (res.ok) {
            showToast("Book removed from catalog.", "success");
            fetchBooks();
            fetchStats();
        } else {
            showToast("Failed to delete book.", "error");
        }
    } catch (e) {
        showToast("Error deleting book.", "error");
    }
}

// ==========================================================================
// Authentication (Strict Architecture)
// ==========================================================================
async function handleLoginSubmit(e) {
    e.preventDefault();
    const userId = document.getElementById("loginUserId").value.trim();
    const pass = document.getElementById("loginPassword").value.trim();
    loginUser(userId, pass);
}

async function loginUser(userId, password) {
    try {
        const res = await fetch("/api/auth/login", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ userId, password })
        });

        const data = await res.json();
        if (res.ok && data.success) {
            state.currentUser = data.user;
            localStorage.setItem("sls_user", JSON.stringify(state.currentUser));
            updateUserUI();
            closeModal("authModal");
            showToast(`👋 Welcome back, ${state.currentUser.name} (${state.currentUser.role})!`, "success");

            fetchUserActivity();
            if (isAdmin()) {
                fetchAdminData();
            } else {
                switchTab("catalogTab");
            }
        } else {
            showToast(data.error || "Invalid User ID or Password.", "error");
        }
    } catch (e) {
        showToast("Network error during login.", "error");
    }
}

function logoutUser() {
    state.currentUser = null;
    localStorage.removeItem("sls_user");
    updateUserUI();
    showToast("Signed out successfully.", "info");
    switchTab("catalogTab");
}

// ==========================================================================
// Storage Mode Toggle (In-Memory / MySQL)
// ==========================================================================
async function toggleDatabaseMode() {
    const isCurrentlyDb = document.getElementById("dbModeText").textContent.includes("MySQL");
    const targetMode = !isCurrentlyDb;

    try {
        const res = await fetch("/api/config/db", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ enable: targetMode })
        });

        const data = await res.json();
        showToast(data.message || (targetMode ? "Switched to MySQL Database" : "Switched to In-Memory mode"), data.success ? "success" : "info");
        fetchHealth();
        fetchBooks();
        fetchStats();
    } catch (e) {
        showToast("Unable to toggle database mode.", "error");
    }
}

// ==========================================================================
// Modal & Toast Helpers
// ==========================================================================
function openModal(modalId) {
    const modal = document.getElementById(modalId);
    if (modal) modal.classList.remove("hidden");
}

function closeModal(modalId) {
    const modal = document.getElementById(modalId);
    if (modal) modal.classList.add("hidden");
}

function showToast(message, type = "info") {
    const container = document.getElementById("toastContainer");
    const toast = document.createElement("div");
    toast.className = `toast toast-${type}`;

    let icon = "ℹ️";
    if (type === "success") icon = "✅";
    if (type === "error") icon = "❌";

    toast.innerHTML = `<span>${icon}</span><span>${escapeHtml(message)}</span>`;
    container.appendChild(toast);

    setTimeout(() => {
        toast.style.opacity = "0";
        toast.style.transform = "translateY(10px)";
        toast.style.transition = "all 0.25s ease";
        setTimeout(() => toast.remove(), 250);
    }, 4000);
}

function escapeHtml(str) {
    if (!str) return "";
    return String(str)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;");
}
