-- =====================================================================
-- Smart Library System - Unified Database Schema & Seed Data (Day 1 to 5)
-- =====================================================================

CREATE DATABASE IF NOT EXISTS library_db;
USE library_db;

-- 1. Libraries Table (Day 3: Location search by city/pincode + distance sorting)
CREATE TABLE IF NOT EXISTS libraries (
    library_id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    pincode VARCHAR(20) NOT NULL,
    location VARCHAR(200) NOT NULL,
    distance_km DECIMAL(6, 2) DEFAULT 1.0,
    contact_number VARCHAR(50)
);

-- 2. Users Table (Day 1: Role, Email regex validation, Password >= 6 chars)
-- Strictly seeded with ONLY Admin. Readers are generated by Admin in the Admin Panel.
CREATE TABLE IF NOT EXISTS users (
    user_id VARCHAR(50) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'READER', -- 'ADMIN' or 'READER'
    created_by_admin BOOLEAN DEFAULT TRUE,
    created_at DATE
);

-- 3. Books Table (Day 1 & Day 3: PhysicalBook, EBook, AudioBook polymorphic types)
CREATE TABLE IF NOT EXISTS books (
    book_id VARCHAR(50) PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    author VARCHAR(100) NOT NULL,
    genre VARCHAR(100) DEFAULT 'General',
    book_type VARCHAR(20) NOT NULL, -- 'PHYSICAL', 'EBOOK', 'AUDIOBOOK'
    buy_price DECIMAL(10, 2) DEFAULT 499.00,
    available_copies INT DEFAULT 1,
    total_copies INT DEFAULT 1,
    shelf_number INT,                 -- For PhysicalBook
    download_link VARCHAR(255),       -- For EBook
    narrator VARCHAR(100),            -- For AudioBook
    audio_duration_minutes INT,       -- For AudioBook
    audio_stream_url VARCHAR(255)     -- For AudioBook
);

-- 4. Transactions Table (Day 4: Buy & Rent Flow, Late Fines, History)
CREATE TABLE IF NOT EXISTS transactions (
    transaction_id VARCHAR(50) PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    book_id VARCHAR(50) NOT NULL,
    book_title VARCHAR(200),
    transaction_type VARCHAR(20) NOT NULL DEFAULT 'RENT', -- 'RENT' or 'BUY'
    issue_date DATE NOT NULL,
    due_date DATE,
    return_date DATE,
    amount_paid DECIMAL(10, 2) NOT NULL,
    overdue_fine DECIMAL(10, 2) DEFAULT 0.00,
    status VARCHAR(20) NOT NULL, -- 'BORROWED', 'RETURNED', 'PURCHASED'
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (book_id) REFERENCES books(book_id) ON DELETE CASCADE
);

-- 5. Reservations Table (Day 4: FIFO Reservation Queue Queue<Reservation>)
CREATE TABLE IF NOT EXISTS reservations (
    reservation_id VARCHAR(50) PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    book_id VARCHAR(50) NOT NULL,
    reservation_date DATE NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING', -- 'PENDING', 'READY', 'FULFILLED', 'CANCELLED'
    queue_position INT DEFAULT 1,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (book_id) REFERENCES books(book_id) ON DELETE CASCADE
);

-- =====================================================================
-- Initial Seed Data
-- =====================================================================

-- STRICT ACCOUNT ARCHITECTURE: Only Admin account pre-seeded!
INSERT IGNORE INTO users (user_id, name, email, password, role, created_by_admin, created_at) VALUES
('admin', 'System Administrator', 'admin@library.edu', 'admin123', 'ADMIN', TRUE, CURDATE()),
('ADMIN-001', 'System Administrator', 'admin@library.edu', 'admin123', 'ADMIN', TRUE, CURDATE());

-- Libraries across cities with pincodes and distances
INSERT IGNORE INTO libraries (library_id, name, city, pincode, location, distance_km, contact_number) VALUES
('LIB-01', 'Central Knowledge Hub', 'Delhi', '110001', 'Connaught Place, Central Wing', 1.20, '+91 11 2345 6789'),
('LIB-02', 'North Campus Academic Library', 'Delhi', '110007', 'University Enclave, North Campus', 3.80, '+91 11 2766 1122'),
('LIB-03', 'South Extension Digital Commons', 'Delhi', '110049', 'Ring Road, South Ext-Part II', 5.40, '+91 11 4164 9900'),
('LIB-04', 'Marine Drive State Library', 'Mumbai', '400020', 'Nariman Point Promenade', 2.10, '+91 22 2281 3400'),
('LIB-05', 'Bandra West Public Reading Room', 'Mumbai', '400050', 'Hill Road, Bandra West', 6.70, '+91 22 2642 7788'),
('LIB-06', 'Indiranagar Tech Library', 'Bengaluru', '560038', '100 Feet Road, Indiranagar', 1.80, '+91 80 2521 8844'),
('LIB-07', 'Koramangala Innovation Commons', 'Bengaluru', '560034', '80 Feet Main Road, 4th Block', 4.20, '+91 80 4123 5500');

-- Books: Physical, E-Book, and AudioBook
INSERT IGNORE INTO books (book_id, title, author, genre, book_type, buy_price, available_copies, total_copies, shelf_number, download_link, narrator, audio_duration_minutes, audio_stream_url) VALUES
('B101', 'Clean Code: A Handbook of Agile Software Craftsmanship', 'Robert C. Martin', 'Computer Science', 'PHYSICAL', 599.00, 3, 3, 101, NULL, NULL, NULL, NULL),
('B102', 'Effective Java (3rd Edition)', 'Joshua Bloch', 'Computer Science', 'PHYSICAL', 649.00, 2, 2, 102, NULL, NULL, NULL, NULL),
('B103', 'Design Patterns: Elements of Reusable Software', 'Gang of Four', 'Software Engineering', 'PHYSICAL', 699.00, 0, 1, 103, NULL, NULL, NULL, NULL),
('B104', 'Introduction to Algorithms (CLRS)', 'Thomas H. Cormen', 'Computer Science', 'PHYSICAL', 899.00, 4, 4, 104, NULL, NULL, NULL, NULL),
('B105', 'The Psychology of Money', 'Morgan Housel', 'Finance & Business', 'PHYSICAL', 399.00, 5, 5, 105, NULL, NULL, NULL, NULL),
('E201', 'Java: The Complete Reference (12th Ed)', 'Herbert Schildt', 'Computer Science', 'EBOOK', 249.00, 10, 10, NULL, 'https://library.edu/ebooks/java-complete-ref.pdf', NULL, NULL, NULL),
('E202', 'Spring Boot in Action', 'Craig Walls', 'Software Engineering', 'EBOOK', 299.00, 10, 10, NULL, 'https://library.edu/ebooks/spring-boot-in-action.pdf', NULL, NULL, NULL),
('E203', 'Database System Concepts', 'Abraham Silberschatz', 'Computer Science', 'EBOOK', 320.00, 10, 10, NULL, 'https://library.edu/ebooks/db-concepts.pdf', NULL, NULL, NULL),
('E204', 'Deep Work: Rules for Focused Success', 'Cal Newport', 'Self-Help', 'EBOOK', 199.00, 10, 10, NULL, 'https://library.edu/ebooks/deep-work.pdf', NULL, NULL, NULL),
('A301', 'Atomic Habits: An Easy & Proven Way', 'James Clear', 'Self-Help', 'AUDIOBOOK', 349.00, 10, 10, NULL, NULL, 'James Clear', 320, 'https://library.edu/audio/atomic-habits-preview.mp3'),
('A302', 'Sapiens: A Brief History of Humankind', 'Yuval Noah Harari', 'History & Science', 'AUDIOBOOK', 399.00, 10, 10, NULL, NULL, 'Derek Perkins', 480, 'https://library.edu/audio/sapiens-preview.mp3');
